#使用hikari连接池
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #账号配置
    url: jdbc:mysql://localhost:3306/item?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #hikari数据库连接池
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 20 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 500 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
  redis:
    host: 39.106.33.10
    port: 6379
    # 密码 没有则可以不填
    password: 123456
    #连接池超时时间（毫秒）
    timeout: 2000000
    # 如果使用的jedis 则将lettuce改成jedis即可
    lettuce:
      pool:
        # 最大活跃链接数（使用负值表示没有限制）
        max-active: 500
        # 最大空闲连接数
        max-idle: 20
        # 最小空闲连接数
        min-idle: 10
        #连接池最大阻塞时间（使用负值表示没有限制）
        max-wait: -1
    # 数据库
    database: 3