spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          url: jdbc:mysql://localhost:3306/item?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall
          #连接池配置
          # 初始化大小，最小，最大
          initialSize: 20
          minIdle: 20
          maxActive: 500
          #连接等待超时时间
          maxWait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
          # 配置DruidStatViewServlet
          #监控地址：http://127.0.0.1:8083/druid/index.html
          stat-view-servlet:
            url-pattern: "/druid/*"
            # IP白名单(没有配置或者为空，则允许所有访问)
            #allow: 127.0.0.1,192.168.163.1
            # IP黑名单 (存在共同时，deny优先于allow)
            deny: 192.168.1.73
            #  禁用HTML页面上的“Reset All”功能
            reset-enable: false
            # 登录名
            login-username: admin
            # 登录密码
            login-password: 123456
    redis:
      host: 39.106.33.10
      port: 6379
      # 密码 没有则可以不填
      password: 123456
      #连接池超时时间（毫秒）
      timeout: 2000000
      # 如果使用的jedis 则将lettuce改成jedis即可
      lettuce:
        pool:
          # 最大活跃链接数（使用负值表示没有限制）
          max-active: 500
          # 最大空闲连接数
          max-idle: 20
          # 最小空闲连接数
          min-idle: 10
          #连接池最大阻塞时间（使用负值表示没有限制）
          max-wait: -1
      # 数据库
      database: 3

#当properties一直中文乱码可以选择在yml里面配置
#或者删除文件properties(不要选safe delete)，然后新建一个文件（记得工程编码指定的是正确的），把内容copy进去，重启，就可以了
info:
  build:
    test2: 测试中文乱码