spring:
    servlet:
      multipart:
        # 最大支持文件大小
        max-file-size: 100MB
        # 最大支持请求大小
        max-request-size: 100MB
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          url: jdbc:mysql://20.1.11.184:3306/item?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: dxyt123
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall
          #连接池配置
          # 初始化大小，最小，最大
          initialSize: 20
          minIdle: 20
          maxActive: 500
          #连接等待超时时间
          maxWait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
          # 配置DruidStatViewServlet
          #监控地址：http://127.0.0.1:8083/druid/index.html
          stat-view-servlet:
            url-pattern: "/druid/*"
            # IP白名单(没有配置或者为空，则允许所有访问)
            #allow: 127.0.0.1,192.168.163.1
            # IP黑名单 (存在共同时，deny优先于allow)
            deny: 192.168.1.73
            #  禁用HTML页面上的“Reset All”功能
            reset-enable: false
            # 登录名
            login-username: admin
            # 登录密码
            login-password: 123456
    redis:
      host: 20.1.11.159
      port: 6379
      # 密码 没有则可以不填
      password:
      # 如果使用的jedis 则将lettuce改成jedis即可
      jedis:
        pool:
          # 最大活跃链接数 默认8
          max-active: 8
          # 最大空闲连接数 默认8
          max-idle: 8
          # 最小空闲连接数 默认0
          min-idle: 0
      # 0号数据库
      database: 3

parameter:
  picture:
    #图片访问的ip和端口
    ip: http://20.1.11.5:8083

dxyt:
  bus:
    push:
      BASE_API_URL: http://20.1.11.52:5988/http/GA000Comm
      BWLYIPDZ: 20.1.11.129
      BWLYDKH: 8080
      FWQQZ_ZCXX: A00111000000000000504
      FWBS: S00111000000000006002
      FFBS: FUN001
      FFMC: notice.createPushByUsername
      PACKAGE_NAME: com.telecomyt.item
      FWQQ_SJSJLX: service_request
      URL: http://39.106.33.10:8083/taskDetail?valueType=%d&groupId=%s&groupStatus=%d&type=notice&current=false